package bean;
// Generated 22/09/2023 19:10:28 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteMabs generated by hbm2java
 */
@Entity
@Table(name="cliente_mabs"
    ,catalog="horifrutibutarellilp"
)
public class ClienteMabs  implements java.io.Serializable {


     private int idClienteMabs;
     private UsuariosMabs usuariosMabs;
     private String nomeMabs;
     private String cpfMabs;
     private Date nascimentoMabs;
     private String cidadeMabs;
     private String numerocasaMabs;
     private String rgMabs;
     private String cepMabs;
     private String emailMabs;
     private String nacionalidadeMabs;
     private String sexoMabs;
     private String estadoMabs;
     private String telefoneMabs;
     private String ruaMabs;
     private String complementoMabs;

    public ClienteMabs() {
    }

    public ClienteMabs(int idClienteMabs, UsuariosMabs usuariosMabs, String nomeMabs, String cpfMabs, Date nascimentoMabs, String cidadeMabs, String numerocasaMabs, String rgMabs, String cepMabs, String emailMabs, String nacionalidadeMabs, String sexoMabs, String estadoMabs, String telefoneMabs, String ruaMabs, String complementoMabs) {
       this.idClienteMabs = idClienteMabs;
       this.usuariosMabs = usuariosMabs;
       this.nomeMabs = nomeMabs;
       this.cpfMabs = cpfMabs;
       this.nascimentoMabs = nascimentoMabs;
       this.cidadeMabs = cidadeMabs;
       this.numerocasaMabs = numerocasaMabs;
       this.rgMabs = rgMabs;
       this.cepMabs = cepMabs;
       this.emailMabs = emailMabs;
       this.nacionalidadeMabs = nacionalidadeMabs;
       this.sexoMabs = sexoMabs;
       this.estadoMabs = estadoMabs;
       this.telefoneMabs = telefoneMabs;
       this.ruaMabs = ruaMabs;
       this.complementoMabs = complementoMabs;
    }
   
     @Id 

    
    @Column(name="id_cliente_mabs", unique=true, nullable=false)
    public int getIdClienteMabs() {
        return this.idClienteMabs;
    }
    
    public void setIdClienteMabs(int idClienteMabs) {
        this.idClienteMabs = idClienteMabs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkusuarios_mabs", nullable=false)
    public UsuariosMabs getUsuariosMabs() {
        return this.usuariosMabs;
    }
    
    public void setUsuariosMabs(UsuariosMabs usuariosMabs) {
        this.usuariosMabs = usuariosMabs;
    }

    
    @Column(name="nome_mabs", nullable=false, length=45)
    public String getNomeMabs() {
        return this.nomeMabs;
    }
    
    public void setNomeMabs(String nomeMabs) {
        this.nomeMabs = nomeMabs;
    }

    
    @Column(name="cpf_mabs", nullable=false, length=15)
    public String getCpfMabs() {
        return this.cpfMabs;
    }
    
    public void setCpfMabs(String cpfMabs) {
        this.cpfMabs = cpfMabs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nascimento_mabs", nullable=false, length=10)
    public Date getNascimentoMabs() {
        return this.nascimentoMabs;
    }
    
    public void setNascimentoMabs(Date nascimentoMabs) {
        this.nascimentoMabs = nascimentoMabs;
    }

    
    @Column(name="cidade_mabs", nullable=false, length=45)
    public String getCidadeMabs() {
        return this.cidadeMabs;
    }
    
    public void setCidadeMabs(String cidadeMabs) {
        this.cidadeMabs = cidadeMabs;
    }

    
    @Column(name="numerocasa_mabs", nullable=false, length=10)
    public String getNumerocasaMabs() {
        return this.numerocasaMabs;
    }
    
    public void setNumerocasaMabs(String numerocasaMabs) {
        this.numerocasaMabs = numerocasaMabs;
    }

    
    @Column(name="rg_mabs", nullable=false, length=15)
    public String getRgMabs() {
        return this.rgMabs;
    }
    
    public void setRgMabs(String rgMabs) {
        this.rgMabs = rgMabs;
    }

    
    @Column(name="cep_mabs", nullable=false, length=15)
    public String getCepMabs() {
        return this.cepMabs;
    }
    
    public void setCepMabs(String cepMabs) {
        this.cepMabs = cepMabs;
    }

    
    @Column(name="email_mabs", nullable=false, length=45)
    public String getEmailMabs() {
        return this.emailMabs;
    }
    
    public void setEmailMabs(String emailMabs) {
        this.emailMabs = emailMabs;
    }

    
    @Column(name="nacionalidade_mabs", nullable=false, length=25)
    public String getNacionalidadeMabs() {
        return this.nacionalidadeMabs;
    }
    
    public void setNacionalidadeMabs(String nacionalidadeMabs) {
        this.nacionalidadeMabs = nacionalidadeMabs;
    }

    
    @Column(name="sexo_mabs", nullable=false, length=2)
    public String getSexoMabs() {
        return this.sexoMabs;
    }
    
    public void setSexoMabs(String sexoMabs) {
        this.sexoMabs = sexoMabs;
    }

    
    @Column(name="estado_mabs", nullable=false, length=15)
    public String getEstadoMabs() {
        return this.estadoMabs;
    }
    
    public void setEstadoMabs(String estadoMabs) {
        this.estadoMabs = estadoMabs;
    }

    
    @Column(name="telefone_mabs", nullable=false, length=25)
    public String getTelefoneMabs() {
        return this.telefoneMabs;
    }
    
    public void setTelefoneMabs(String telefoneMabs) {
        this.telefoneMabs = telefoneMabs;
    }

    
    @Column(name="rua_mabs", nullable=false, length=25)
    public String getRuaMabs() {
        return this.ruaMabs;
    }
    
    public void setRuaMabs(String ruaMabs) {
        this.ruaMabs = ruaMabs;
    }

    
    @Column(name="complemento_mabs", nullable=false, length=20)
    public String getComplementoMabs() {
        return this.complementoMabs;
    }
    
    public void setComplementoMabs(String complementoMabs) {
        this.complementoMabs = complementoMabs;
    }

 @Override
     public String toString() {
    return nomeMabs;
} // O método toString() é usado para fornecer uma representação em forma de string do objeto.
     
     
     @Override
      public boolean equals (Object object){
      if(object instanceof ClienteMabs){
      // Verifica se o objeto passado como argumento é uma instância de MmsCliente
      ClienteMabs clienteMabs = (ClienteMabs) object;
      // Converte o objeto genérico para o tipo MmsCliente
        if(this.getIdClienteMabs()== clienteMabs.getIdClienteMabs())
              // Compara os IDs dos objetos atual e recebido como parâmetro
            return true;
             // Se os IDs forem iguais, retorna verdadeiro (indicando que os objetos são iguais)
                }         
                return false;
                    // Se não for uma instância de cliente ou os IDs forem diferentes, retorna falso

                    //essa função é usada no cbo para igualar as fks de cliente no banco de dados
      }
         
}





