package bean;
// Generated 22/09/2023 19:10:28 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.Date;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComprasMabs generated by hbm2java
 */
@Entity
@Table(name="compras_mabs"
    ,catalog="horifrutibutarellilp"
)
public class ComprasMabs  implements java.io.Serializable {


     private int idComprasMabs;
     private FornecedorMabs fornecedorMabs;
     private Double totalMabs;
     private ClienteMabs clienteMabs;
     private Date dataMabs;
     

    public ComprasMabs() {
    }

	
    public ComprasMabs(int idComprasMabs, FornecedorMabs fornecedorMabs, Double totalMabs, ClienteMabs clienteMabs, Date dataMabs) {
        this.idComprasMabs = idComprasMabs;
        this.fornecedorMabs = fornecedorMabs;
        this.dataMabs = dataMabs;
        this.totalMabs = totalMabs;
        this.clienteMabs = clienteMabs;
    }
    public ComprasMabs(int idComprasMabs, FornecedorMabs fornecedorMabs, Double totalMabs ,Set comprasProdutoMabses, ClienteMabs clienteMabs, Date dataMabs) {
       this.idComprasMabs = idComprasMabs;
       this.fornecedorMabs = fornecedorMabs;
       this.dataMabs = dataMabs;
       this.totalMabs = totalMabs;
       this.clienteMabs = clienteMabs;
    }
   
     @Id 

    
    @Column(name="id_compras_mabs", unique=true, nullable=false)
    public int getIdComprasMabs() {
        return this.idComprasMabs;
    }
    
    public void setIdComprasMabs(int idComprasMabs) {
        this.idComprasMabs = idComprasMabs;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fkfornecedor_mabs", nullable=false)
    public FornecedorMabs getFornecedorMabs() {
        return this.fornecedorMabs;
    }
    
    public void setFornecedorMabs(FornecedorMabs fornecedorMabs) {
        this.fornecedorMabs = fornecedorMabs;
    }

    
   @Temporal(TemporalType.DATE)
    @Column(name="data_mabs", nullable=false, length=10)
    public Date getDataMabs() {
        return this.dataMabs;
    }
    
    public void setDataMabs(Date dataMabs) {
        this.dataMabs = dataMabs;
    }
    
    @Column(name="total_mabs", nullable=false, precision=5)
    public Double getTotalMabs() {
        return this.totalMabs;
    }
    
    public void setTotalMabs(Double totalMabs) {
        this.totalMabs = totalMabs;
    }

    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fkcliente_mabs", nullable=false)
    public ClienteMabs getClienteMabs() {
        return this.clienteMabs;
    }
    
    public void setClienteMabs(ClienteMabs clienteMabs) {
        this.clienteMabs = clienteMabs;
    }




}


