package bean;
// Generated 22/09/2023 19:10:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FornecedorMabs generated by hbm2java
 */
@Entity
@Table(name="fornecedor_mabs"
    ,catalog="horifrutibutarellilp"
)
public class FornecedorMabs  implements java.io.Serializable {


     private int idFornecedorMabs;
     private UsuariosMabs usuariosMabs;
     private String telefoneMabs;
     private String sexoMabs;
     private String nacionalidadeMabs;
     private String estadoMabs;
     private String cidadeMabs;
     private String cepMabs;
     private String numerohomeMabs;
     private String ruaMabs;
     private String complementoMabs;
     private String nomeMabs;

    public FornecedorMabs() {
    }

	
    public FornecedorMabs(int idFornecedorMabs, UsuariosMabs usuariosMabs, String telefoneMabs, String sexoMabs, String nacionalidadeMabs, String estadoMabs, String cidadeMabs, String cepMabs, String numerohomeMabs, String ruaMabs, String complementoMabs, String nomeMabs) {
        this.idFornecedorMabs = idFornecedorMabs;
        this.usuariosMabs = usuariosMabs;
        this.telefoneMabs = telefoneMabs;
        this.sexoMabs = sexoMabs;
        this.nacionalidadeMabs = nacionalidadeMabs;
        this.estadoMabs = estadoMabs;
        this.cidadeMabs = cidadeMabs;
        this.cepMabs = cepMabs;
        this.numerohomeMabs = numerohomeMabs;
        this.ruaMabs = ruaMabs;
        this.complementoMabs = complementoMabs;
        this.nomeMabs = nomeMabs;
    }
    public FornecedorMabs(int idFornecedorMabs, UsuariosMabs usuariosMabs, String telefoneMabs, String sexoMabs, String nacionalidadeMabs, String estadoMabs, String cidadeMabs, String cepMabs, String numerohomeMabs, String ruaMabs, String complementoMabs, Set comprasMabses, String nomeMabs) {
       this.idFornecedorMabs = idFornecedorMabs;
       this.usuariosMabs = usuariosMabs;
       this.telefoneMabs = telefoneMabs;
       this.sexoMabs = sexoMabs;
       this.nacionalidadeMabs = nacionalidadeMabs;
       this.estadoMabs = estadoMabs;
       this.cidadeMabs = cidadeMabs;
       this.cepMabs = cepMabs;
       this.numerohomeMabs = numerohomeMabs;
       this.ruaMabs = ruaMabs;
       this.complementoMabs = complementoMabs;
       this.nomeMabs = nomeMabs;
    }
   
     @Id 

    
    @Column(name="id_fornecedor_mabs", unique=true, nullable=false)
    public int getIdFornecedorMabs() {
        return this.idFornecedorMabs;
    }
    
    public void setIdFornecedorMabs(int idFornecedorMabs) {
        this.idFornecedorMabs = idFornecedorMabs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkusuarios_mabs", nullable=false) 
    public UsuariosMabs getUsuariosMabs() {
        return this.usuariosMabs;
    }
    
    public void setUsuariosMabs(UsuariosMabs usuariosMabs) {
        this.usuariosMabs = usuariosMabs;
    }

    
    @Column(name="telefone_mabs", nullable=false, length=18)
    public String getTelefoneMabs() {
        return this.telefoneMabs;
    }
    
    public void setTelefoneMabs(String telefoneMabs) {
        this.telefoneMabs = telefoneMabs;
    }

    
    @Column(name="sexo_mabs", nullable=false, length=2)
    public String getSexoMabs() {
        return this.sexoMabs;
    }
    
    public void setSexoMabs(String sexoMabs) {
        this.sexoMabs = sexoMabs;
    }

    
    @Column(name="nacionalidade_mabs", nullable=false, length=25)
    public String getNacionalidadeMabs() {
        return this.nacionalidadeMabs;
    }
    
    public void setNacionalidadeMabs(String nacionalidadeMabs) {
        this.nacionalidadeMabs = nacionalidadeMabs;
    }

    
    @Column(name="estado_mabs", nullable=false, length=3)
    public String getEstadoMabs() {
        return this.estadoMabs;
    }
    
    public void setEstadoMabs(String estadoMabs) {
        this.estadoMabs = estadoMabs;
    }

    
    @Column(name="cidade_mabs", nullable=false, length=45)
    public String getCidadeMabs() {
        return this.cidadeMabs;
    }
    
    public void setCidadeMabs(String cidadeMabs) {
        this.cidadeMabs = cidadeMabs;
    }

    
    @Column(name="cep_mabs", nullable=false, length=13)
    public String getCepMabs() {
        return this.cepMabs;
    }
    
    public void setCepMabs(String cepMabs) {
        this.cepMabs = cepMabs;
    }

    
    @Column(name="numerohome_mabs", nullable=false, length=10)
    public String getNumerohomeMabs() {
        return this.numerohomeMabs;
    }
    
    public void setNumerohomeMabs(String numerohomeMabs) {
        this.numerohomeMabs = numerohomeMabs;
    }

    
    @Column(name="rua_mabs", nullable=false, length=25)
    public String getRuaMabs() {
        return this.ruaMabs;
    }
    
    public void setRuaMabs(String ruaMabs) {
        this.ruaMabs = ruaMabs;
    }

    
    @Column(name="complemento_mabs", nullable=false, length=20)
    public String getComplementoMabs() {
        return this.complementoMabs;
    }
    
    public void setComplementoMabs(String complementoMabs) {
        this.complementoMabs = complementoMabs;
    }
    
    @Column(name="nome_mabs", nullable=false, length=45)
    public String getNomeMabs() {
        return this.nomeMabs;
    }
    
    public void setNomeMabs(String nomeMabs) {
        this.nomeMabs = nomeMabs;
    }

     @Override
    public String toString(){
    return this.getNomeMabs();
    }
     
    public boolean equals (Object object){
    if(object instanceof FornecedorMabs){
      FornecedorMabs fornecedorMabs = (FornecedorMabs) object;
    if(this.getIdFornecedorMabs()==fornecedorMabs.getIdFornecedorMabs()){
    return true;
    } }
    return false;
}

}





