package bean;
// Generated 22/09/2023 19:10:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProdutosMabs generated by hbm2java
 */
@Entity
@Table(name="produtos_mabs"
    ,catalog="horifrutibutarellilp"
)
public class ProdutosMabs  implements java.io.Serializable {


     private int idProdutosMabs;
     private String tipoMabs;
     private String pesoMabs;
     private String conservantesMabs;
     private String nomealimentoMabs;
     private Date validadeMabs;
     private Double valorunitarioMabs;
     
    public ProdutosMabs() {
    }

	
    public ProdutosMabs(int idProdutosMabs, String tipoMabs, String pesoMabs, String conservantesMabs, String nomealimentoMabs, Date validadeMabs, Double valorunitarioMabs) {
        this.idProdutosMabs = idProdutosMabs;
        this.tipoMabs = tipoMabs;
        this.pesoMabs = pesoMabs;
        this.conservantesMabs = conservantesMabs;
        this.nomealimentoMabs = nomealimentoMabs;
        this.validadeMabs = validadeMabs;
        this.valorunitarioMabs = valorunitarioMabs;
    }
    public ProdutosMabs(int idProdutosMabs, String tipoMabs, String pesoMabs, String conservantesMabs, String nomealimentoMabs, Date validadeMabs, Set comprasProdutoMabses, Set comprasMabses, Double valorunitarioMabs) {
       this.idProdutosMabs = idProdutosMabs;
       this.tipoMabs = tipoMabs;
       this.pesoMabs = pesoMabs;
       this.conservantesMabs = conservantesMabs;
       this.nomealimentoMabs = nomealimentoMabs;
       this.validadeMabs = validadeMabs;
       this.valorunitarioMabs = valorunitarioMabs;
     
    }
   
     @Id 

    
    @Column(name="id_produtos_mabs", unique=true, nullable=false)
    public int getIdProdutosMabs() {
        return this.idProdutosMabs;
    }
    
    public void setIdProdutosMabs(int idProdutosMabs) {
        this.idProdutosMabs = idProdutosMabs;
    }

    
    @Column(name="tipo_mabs", nullable=false, length=15)
    public String getTipoMabs() {
        return this.tipoMabs;
    }
    
    public void setTipoMabs(String tipoMabs) {
        this.tipoMabs = tipoMabs;
    }

    
    @Column(name="peso_mabs", nullable=false, length=10)
    public String getPesoMabs() {
        return this.pesoMabs;
    }
    
    public void setPesoMabs(String pesoMabs) {
        this.pesoMabs = pesoMabs;
    }

    
    @Column(name="conservantes_mabs", nullable=false, length=3)
    public String getConservantesMabs() {
        return this.conservantesMabs;
    }
    
    public void setConservantesMabs(String conservantesMabs) {
        this.conservantesMabs = conservantesMabs;
    }

    
    @Column(name="nomealimento_mabs", nullable=false, length=20)
    public String getNomealimentoMabs() {
        return this.nomealimentoMabs;
    }
    
    public void setNomealimentoMabs(String nomealimentoMabs) {
        this.nomealimentoMabs = nomealimentoMabs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="validade_mabs", nullable=false, length=10)
    public Date getValidadeMabs() {
        return this.validadeMabs;
    }
    
    public void setValidadeMabs(Date validadeMabs) {
        this.validadeMabs = validadeMabs;
    }

@Column(name="valorunitario_mabs", nullable=false, precision=5)
    public Double getValorUnitarioMabs() {
        return this.valorunitarioMabs;
    }

    public void setValorUnitarioMabs(Double valorunitarioMabs) {
        this.valorunitarioMabs = valorunitarioMabs;
    }
    
 public String toString(){
    return this.getNomealimentoMabs();
    }
    @Override
    public boolean equals (Object object){
    if(object instanceof ProdutosMabs){
        ProdutosMabs produtosMabs = (ProdutosMabs) object;
    if(this.getIdProdutosMabs()==produtosMabs.getIdProdutosMabs()){
    return true;
    } }
    return false;
}

    
}


