package bean;
// Generated 22/09/2023 19:10:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosMabs generated by hbm2java
 */
@Entity
@Table(name="usuarios_mabs"
    ,catalog="horifrutibutarellilp"
)
public class UsuariosMabs  implements java.io.Serializable {


     private int idUsuariosMabs;
     private String nomeMabs;
     private String nicknameMabs;
     private String cpfMabs;
     private Date dataNasceMabs;
     private String senhaMabs;
     private int nvlpermisoMabs;
     private String ativoMabs;
    

    public UsuariosMabs() {
    }

	
    public UsuariosMabs(int idUsuariosMabs, String nomeMabs, String nicknameMabs, String cpfMabs, Date dataNasceMabs, String senhaMabs, int nvlpermisoMabs, String ativoMabs) {
        this.idUsuariosMabs = idUsuariosMabs;
        this.nomeMabs = nomeMabs;
        this.nicknameMabs = nicknameMabs;
        this.cpfMabs = cpfMabs;
        this.dataNasceMabs = dataNasceMabs;
        this.senhaMabs = senhaMabs;
        this.nvlpermisoMabs = nvlpermisoMabs;
        this.ativoMabs = ativoMabs;
    }
    public UsuariosMabs(int idUsuariosMabs, String nomeMabs, String nicknameMabs, String cpfMabs, Date dataNasceMabs, String senhaMabs, int nvlpermisoMabs, String ativoMabs, Set fornecedorMabses, Set clienteMabses) {
       this.idUsuariosMabs = idUsuariosMabs;
       this.nomeMabs = nomeMabs;
       this.nicknameMabs = nicknameMabs;
       this.cpfMabs = cpfMabs;
       this.dataNasceMabs = dataNasceMabs;
       this.senhaMabs = senhaMabs;
       this.nvlpermisoMabs = nvlpermisoMabs;
       this.ativoMabs = ativoMabs;
       
    }
   
     @Id 

    
    @Column(name="id_usuarios_mabs", unique=true, nullable=false)
    public int getIdUsuariosMabs() {
        return this.idUsuariosMabs;
    }
    
    public void setIdUsuariosMabs(int idUsuariosMabs) {
        this.idUsuariosMabs = idUsuariosMabs;
    }

    
    @Column(name="nome_mabs", nullable=false, length=45)
    public String getNomeMabs() {
        return this.nomeMabs;
    }
    
    public void setNomeMabs(String nomeMabs) {
        this.nomeMabs = nomeMabs;
    }

    
    @Column(name="nickname_mabs", nullable=false, length=20)
    public String getNicknameMabs() {
        return this.nicknameMabs;
    }
    
    public void setNicknameMabs(String nicknameMabs) {
        this.nicknameMabs = nicknameMabs;
    }

    
    @Column(name="cpf_mabs", nullable=false, length=25)
    public String getCpfMabs() {
        return this.cpfMabs;
    }
    
    public void setCpfMabs(String cpfMabs) {
        this.cpfMabs = cpfMabs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNasce_mabs", nullable=false, length=10)
    public Date getDataNasceMabs() {
        return this.dataNasceMabs;
    }
    
    public void setDataNasceMabs(Date dataNasceMabs) {
        this.dataNasceMabs = dataNasceMabs;
    }

    
    @Column(name="senha_mabs", nullable=false, length=20)
    public String getSenhaMabs() {
        return this.senhaMabs;
    }
    
    public void setSenhaMabs(String senhaMabs) {
        this.senhaMabs = senhaMabs;
    }

    
    @Column(name="nvlpermiso_mabs", nullable=false)
    public int getNvlpermisoMabs() {
        return this.nvlpermisoMabs;
    }
    
    public void setNvlpermisoMabs(int nvlpermisoMabs) {
        this.nvlpermisoMabs = nvlpermisoMabs;
    }

    
    @Column(name="ativo_mabs", nullable=false, length=1)
    public String getAtivoMabs() {
        return this.ativoMabs;
    }
    
    public void setAtivoMabs(String ativoMabs) {
        this.ativoMabs = ativoMabs;
    }




}


